"""initial schema

Revision ID: faf0983d7e91
Revises: 
Create Date: 2026-05-23 13:55:49.223902
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'faf0983d7e91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=True),
    sa.Column('api_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=False),
    sa.Column('advance_notice', sa.Integer(), nullable=True),
    sa.Column('repeat_rule', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_status', 'reminders', ['status'], unique=False)
    op.create_index('ix_reminders_user_id', 'reminders', ['user_id'], unique=False)
    op.create_index('ix_reminders_user_status', 'reminders', ['user_id', 'status'], unique=False)
    op.create_table('event_triggers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reminder_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id')
    )
    op.create_table('reminder_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reminder_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminder_history_reminder_id', 'reminder_history', ['reminder_id'], unique=False)
    op.create_index('ix_reminder_history_triggered_at', 'reminder_history', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminder_history_triggered_at', table_name='reminder_history')
    op.drop_index('ix_reminder_history_reminder_id', table_name='reminder_history')
    op.drop_table('reminder_history')
    op.drop_table('event_triggers')
    op.drop_index('ix_reminders_user_status', table_name='reminders')
    op.drop_index('ix_reminders_user_id', table_name='reminders')
    op.drop_index('ix_reminders_status', table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
